### ISSUE TITLE
Increase visibility to items in lib/src

### ISSUE THREAD

**Issue by alevinetx** [mastodon-dart/mastodon-api#94]
mastodon_api: ^0.2.2

Example:

```Future<MastodonResponse<List<Rule>>>  server.v1.instance.lookupRules()```

```lookupRules()``` is contained in ```InstanceV1Service```, which doesn't appear in the documentation.
```Rule``` doesn't appear in the documentation.
IDE cannot find ```Rule``` to understand its data type unless I explicitly import ```package:mastodon_api/src/service/entities/rule.dart```

# 2. Why should this be improved

Beyond improving IDE interaction, this should help improve the generated documentation; there are currently missing items.

# 3. Any risks?

?

**Comment by myConsciousness** [comment]
Hi @alevinetx , thanks for your feedback :)

I understand, but it's difficult from a development resource perspective to write a description of all model objects provided in this package in a README or similar document. Also, these model objects have the same structure as the official mastodon entities, and I feel I would be better off reading the official references that are already in place.

The structure of the service in which the endpoints are implemented is also the same as the official mastodon, and mappings exist in the following sections :)

- https://github.com/mastodon-dart/mastodon-api#1311-v1

**Comment by alevinetx** [comment]
Hello! 

 I'm not suggesting adding manual documentation, but rather adding additional exports in lib/mastodon_api.dart

**Comment by myConsciousness** [comment]
@alevinetx ,

Oh my bad, I was not aware that these objects are not publicly available!

Would you be interested in a pull request for this Issue? :)

**Comment by alevinetx** [comment]
Sure, let me see what I can do
